http:
  middlewares:
    middleware-crowdsec:
      plugin:
        bouncer:
          enabled: true
          crowdsecMode: stream
          crowdsecAppsecEnabled: true
          crowdsecAppsecHost: crowdsec:7422
          crowdsecAppsecFailureBlock: false
          crowdsecAppsecUnreachableBlock: false
          crowdsecAppsecBodyLimit: 10485760
          crowdsecLapiKey: KQyWziTV9wT3cwItTzKuhf/qIPNPDyV6e7OE1C4+s4g
          crowdsecLapiHost: crowdsec:9879
          crowdsecLapiScheme: http
          crowdsecLapiTLSInsecureVerify: true
          forwardedHeadersTrustedIPs:
            - 10.0.0.0/8
            - 172.16.0.0/12
            - 192.168.0.0/16
          clientTrustedIPs:
            - 10.0.0.0/8
            - 172.16.0.0/12
            - 192.168.0.0/16